name: Issue report
description: Report an issue in Anizuno
labels: [Bug]
body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: anizuno-version
    attributes:
      label: Anizuno version
      description: You can find your Ink version in your phone settings in android or IOS check into TestFight.
      placeholder: |
        Example: "1.0"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: You can find this in your phone settings.
      placeholder: |
        Example: "Android 12"

  - type: input
    id: ios-version
    attributes:
      label: IOS version
      description: You can find this in your phone settings.
      placeholder: |
        Example: "IOS 16.0"

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device and model.
      placeholder: |
        Example:
          "Google Pixel 7"
          "iPhone 15"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true